/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.test_20apr.bmgf_investments2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * AttributeCategoryCode generated by hbm2java
 */
@Entity
@Table(name="`AttributeCategoryCode`"
    ,schema="dbo"
)

public class AttributeCategoryCode  implements java.io.Serializable {

    
    private String attributeCategoryCodeId;
    
    private String attributeCategoryId;
    
    private String attributeName;
    
    private Integer codeDisplayOrder;

    public AttributeCategoryCode() {
    }


    @Id 
    

    @Column(name="`AttributeCategoryCodeID`", length=36)
    public String getAttributeCategoryCodeId() {
        return this.attributeCategoryCodeId;
    }
    
    public void setAttributeCategoryCodeId(String attributeCategoryCodeId) {
        this.attributeCategoryCodeId = attributeCategoryCodeId;
    }

    

    @Column(name="`AttributeCategoryID`", length=36)
    public String getAttributeCategoryId() {
        return this.attributeCategoryId;
    }
    
    public void setAttributeCategoryId(String attributeCategoryId) {
        this.attributeCategoryId = attributeCategoryId;
    }

    

    @Column(name="`AttributeName`")
    public String getAttributeName() {
        return this.attributeName;
    }
    
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    

    @Column(name="`CodeDisplayOrder`", precision=10)
    public Integer getCodeDisplayOrder() {
        return this.codeDisplayOrder;
    }
    
    public void setCodeDisplayOrder(Integer codeDisplayOrder) {
        this.codeDisplayOrder = codeDisplayOrder;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof AttributeCategoryCode) )
		    return false;

		 AttributeCategoryCode that = (AttributeCategoryCode) o;

		 return ( (this.getAttributeCategoryCodeId()==that.getAttributeCategoryCodeId()) || ( this.getAttributeCategoryCodeId()!=null && that.getAttributeCategoryCodeId()!=null && this.getAttributeCategoryCodeId().equals(that.getAttributeCategoryCodeId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getAttributeCategoryCodeId() == null ? 0 : this.getAttributeCategoryCodeId().hashCode() );

         return result;
    }


}

