/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.test_20apr.bmgf_investments2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * InvestmentAttribute generated by hbm2java
 */
@Entity
@Table(name="`InvestmentAttribute`"
    ,schema="dbo"
)

public class InvestmentAttribute  implements java.io.Serializable {

    
    private String investmentAttributeId;
    
    private String investmentId;
    
    private String relatedTable;
    
    private String attributeCategoryId;
    
    private String categoryName;
    
    private Boolean mandatoryAttribute;
    
    private Integer categoryDisplayOrder;

    public InvestmentAttribute() {
    }


    @Id 
    

    @Column(name="`InvestmentAttributeID`", length=36)
    public String getInvestmentAttributeId() {
        return this.investmentAttributeId;
    }
    
    public void setInvestmentAttributeId(String investmentAttributeId) {
        this.investmentAttributeId = investmentAttributeId;
    }

    

    @Column(name="`InvestmentID`", length=36)
    public String getInvestmentId() {
        return this.investmentId;
    }
    
    public void setInvestmentId(String investmentId) {
        this.investmentId = investmentId;
    }

    

    @Column(name="`RelatedTable`")
    public String getRelatedTable() {
        return this.relatedTable;
    }
    
    public void setRelatedTable(String relatedTable) {
        this.relatedTable = relatedTable;
    }

    

    @Column(name="`AttributeCategoryID`", length=36)
    public String getAttributeCategoryId() {
        return this.attributeCategoryId;
    }
    
    public void setAttributeCategoryId(String attributeCategoryId) {
        this.attributeCategoryId = attributeCategoryId;
    }

    

    @Column(name="`CategoryName`")
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    

    @Column(name="`MandatoryAttribute`")
    public Boolean getMandatoryAttribute() {
        return this.mandatoryAttribute;
    }
    
    public void setMandatoryAttribute(Boolean mandatoryAttribute) {
        this.mandatoryAttribute = mandatoryAttribute;
    }

    

    @Column(name="`CategoryDisplayOrder`", precision=10)
    public Integer getCategoryDisplayOrder() {
        return this.categoryDisplayOrder;
    }
    
    public void setCategoryDisplayOrder(Integer categoryDisplayOrder) {
        this.categoryDisplayOrder = categoryDisplayOrder;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof InvestmentAttribute) )
		    return false;

		 InvestmentAttribute that = (InvestmentAttribute) o;

		 return ( (this.getInvestmentAttributeId()==that.getInvestmentAttributeId()) || ( this.getInvestmentAttributeId()!=null && that.getInvestmentAttributeId()!=null && this.getInvestmentAttributeId().equals(that.getInvestmentAttributeId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getInvestmentAttributeId() == null ? 0 : this.getInvestmentAttributeId().hashCode() );

         return result;
    }


}

