/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.test_20apr.bmgf_investments2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Status generated by hbm2java
 */
@Entity
@Table(name="`Status`"
    ,schema="dbo"
)

public class Status  implements java.io.Serializable {

    
    private String statusId;
    
    private String statusDescription;
    
    private Set<Investment> investments = new HashSet<Investment>(0);

    public Status() {
    }


    @Id 
    

    @Column(name="`StatusID`", length=36)
    public String getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }

    

    @Column(name="`StatusDescription`")
    public String getStatusDescription() {
        return this.statusDescription;
    }
    
    public void setStatusDescription(String statusDescription) {
        this.statusDescription = statusDescription;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="status")
    public Set<Investment> getInvestments() {
        return this.investments;
    }
    
    public void setInvestments(Set<Investment> investments) {
        this.investments = investments;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Status) )
		    return false;

		 Status that = (Status) o;

		 return ( (this.getStatusId()==that.getStatusId()) || ( this.getStatusId()!=null && that.getStatusId()!=null && this.getStatusId().equals(that.getStatusId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getStatusId() == null ? 0 : this.getStatusId().hashCode() );

         return result;
    }


}

