/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.test_20apr.bmgf_investments2;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * VwInvestmentAttributesAndCodes generated by hbm2java
 */
@Entity
@Table(name="`vw_InvestmentAttributesAndCodes`"
    ,schema="dbo"
)
@IdClass(value=VwInvestmentAttributesAndCodesId.class)
public class VwInvestmentAttributesAndCodes  implements java.io.Serializable {

    
    private String investmentId;
    
    private String investmentName;
    
    private String programId;
    
    private String programName;
    
    private String strategyId;
    
    private String strategyName;
    
    private String initiativeId;
    
    private String initiativeName;
    
    private String subInitiativeId;
    
    private String subInitiativeName;
    
    private String keyElementId;
    
    private String keyElementName;
    
    private String statusId;
    
    private String statusDescription;
    
    private String investmentAttributeId;
    
    private String attributeCategoryId;
    
    private String categoryName;
    
    private String attributeGroupId;
    
    private String groupingName;
    
    private String investmentAttributeCodeId;
    
    private String attributeName;
    
    private Float distributionPercent;

    public VwInvestmentAttributesAndCodes() {
    }


    @Id 
    

    @Column(name="`InvestmentID`", insertable=false, updatable=false, length=36)
    public String getInvestmentId() {
        return this.investmentId;
    }
    
    public void setInvestmentId(String investmentId) {
        this.investmentId = investmentId;
    }
    @Id 
    

    @Column(name="`InvestmentName`", insertable=false, updatable=false)
    public String getInvestmentName() {
        return this.investmentName;
    }
    
    public void setInvestmentName(String investmentName) {
        this.investmentName = investmentName;
    }
    @Id 
    

    @Column(name="`ProgramID`", insertable=false, updatable=false, length=36)
    public String getProgramId() {
        return this.programId;
    }
    
    public void setProgramId(String programId) {
        this.programId = programId;
    }
    @Id 
    

    @Column(name="`ProgramName`", insertable=false, updatable=false)
    public String getProgramName() {
        return this.programName;
    }
    
    public void setProgramName(String programName) {
        this.programName = programName;
    }
    @Id 
    

    @Column(name="`StrategyID`", insertable=false, updatable=false, length=36)
    public String getStrategyId() {
        return this.strategyId;
    }
    
    public void setStrategyId(String strategyId) {
        this.strategyId = strategyId;
    }
    @Id 
    

    @Column(name="`StrategyName`", insertable=false, updatable=false)
    public String getStrategyName() {
        return this.strategyName;
    }
    
    public void setStrategyName(String strategyName) {
        this.strategyName = strategyName;
    }
    @Id 
    

    @Column(name="`InitiativeID`", insertable=false, updatable=false, length=36)
    public String getInitiativeId() {
        return this.initiativeId;
    }
    
    public void setInitiativeId(String initiativeId) {
        this.initiativeId = initiativeId;
    }
    @Id 
    

    @Column(name="`InitiativeName`", insertable=false, updatable=false)
    public String getInitiativeName() {
        return this.initiativeName;
    }
    
    public void setInitiativeName(String initiativeName) {
        this.initiativeName = initiativeName;
    }
    @Id 
    

    @Column(name="`SubInitiativeID`", insertable=false, updatable=false, length=36)
    public String getSubInitiativeId() {
        return this.subInitiativeId;
    }
    
    public void setSubInitiativeId(String subInitiativeId) {
        this.subInitiativeId = subInitiativeId;
    }
    @Id 
    

    @Column(name="`SubInitiativeName`", insertable=false, updatable=false)
    public String getSubInitiativeName() {
        return this.subInitiativeName;
    }
    
    public void setSubInitiativeName(String subInitiativeName) {
        this.subInitiativeName = subInitiativeName;
    }
    @Id 
    

    @Column(name="`KeyElementID`", insertable=false, updatable=false, length=36)
    public String getKeyElementId() {
        return this.keyElementId;
    }
    
    public void setKeyElementId(String keyElementId) {
        this.keyElementId = keyElementId;
    }
    @Id 
    

    @Column(name="`KeyElementName`", insertable=false, updatable=false)
    public String getKeyElementName() {
        return this.keyElementName;
    }
    
    public void setKeyElementName(String keyElementName) {
        this.keyElementName = keyElementName;
    }
    @Id 
    

    @Column(name="`StatusID`", insertable=false, updatable=false, length=36)
    public String getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(String statusId) {
        this.statusId = statusId;
    }
    @Id 
    

    @Column(name="`StatusDescription`", insertable=false, updatable=false)
    public String getStatusDescription() {
        return this.statusDescription;
    }
    
    public void setStatusDescription(String statusDescription) {
        this.statusDescription = statusDescription;
    }
    @Id 
    

    @Column(name="`InvestmentAttributeID`", insertable=false, updatable=false, length=36)
    public String getInvestmentAttributeId() {
        return this.investmentAttributeId;
    }
    
    public void setInvestmentAttributeId(String investmentAttributeId) {
        this.investmentAttributeId = investmentAttributeId;
    }
    @Id 
    

    @Column(name="`AttributeCategoryID`", insertable=false, updatable=false, length=36)
    public String getAttributeCategoryId() {
        return this.attributeCategoryId;
    }
    
    public void setAttributeCategoryId(String attributeCategoryId) {
        this.attributeCategoryId = attributeCategoryId;
    }
    @Id 
    

    @Column(name="`CategoryName`", insertable=false, updatable=false)
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }
    @Id 
    

    @Column(name="`AttributeGroupID`", insertable=false, updatable=false, length=36)
    public String getAttributeGroupId() {
        return this.attributeGroupId;
    }
    
    public void setAttributeGroupId(String attributeGroupId) {
        this.attributeGroupId = attributeGroupId;
    }
    @Id 
    

    @Column(name="`GroupingName`", insertable=false, updatable=false)
    public String getGroupingName() {
        return this.groupingName;
    }
    
    public void setGroupingName(String groupingName) {
        this.groupingName = groupingName;
    }
    @Id 
    

    @Column(name="`InvestmentAttributeCodeID`", insertable=false, updatable=false, length=36)
    public String getInvestmentAttributeCodeId() {
        return this.investmentAttributeCodeId;
    }
    
    public void setInvestmentAttributeCodeId(String investmentAttributeCodeId) {
        this.investmentAttributeCodeId = investmentAttributeCodeId;
    }
    @Id 
    

    @Column(name="`AttributeName`", insertable=false, updatable=false)
    public String getAttributeName() {
        return this.attributeName;
    }
    
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }
    @Id 
    

    @Column(name="`DistributionPercent`", insertable=false, updatable=false, precision=5)
    public Float getDistributionPercent() {
        return this.distributionPercent;
    }
    
    public void setDistributionPercent(Float distributionPercent) {
        this.distributionPercent = distributionPercent;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof VwInvestmentAttributesAndCodes) )
		    return false;

		 VwInvestmentAttributesAndCodes that = (VwInvestmentAttributesAndCodes) o;

         return ( (this.getInvestmentId()==that.getInvestmentId()) || ( this.getInvestmentId()!=null && that.getInvestmentId()!=null && this.getInvestmentId().equals(that.getInvestmentId()) ) )
 && ( (this.getInvestmentName()==that.getInvestmentName()) || ( this.getInvestmentName()!=null && that.getInvestmentName()!=null && this.getInvestmentName().equals(that.getInvestmentName()) ) )
 && ( (this.getProgramId()==that.getProgramId()) || ( this.getProgramId()!=null && that.getProgramId()!=null && this.getProgramId().equals(that.getProgramId()) ) )
 && ( (this.getProgramName()==that.getProgramName()) || ( this.getProgramName()!=null && that.getProgramName()!=null && this.getProgramName().equals(that.getProgramName()) ) )
 && ( (this.getStrategyId()==that.getStrategyId()) || ( this.getStrategyId()!=null && that.getStrategyId()!=null && this.getStrategyId().equals(that.getStrategyId()) ) )
 && ( (this.getStrategyName()==that.getStrategyName()) || ( this.getStrategyName()!=null && that.getStrategyName()!=null && this.getStrategyName().equals(that.getStrategyName()) ) )
 && ( (this.getInitiativeId()==that.getInitiativeId()) || ( this.getInitiativeId()!=null && that.getInitiativeId()!=null && this.getInitiativeId().equals(that.getInitiativeId()) ) )
 && ( (this.getInitiativeName()==that.getInitiativeName()) || ( this.getInitiativeName()!=null && that.getInitiativeName()!=null && this.getInitiativeName().equals(that.getInitiativeName()) ) )
 && ( (this.getSubInitiativeId()==that.getSubInitiativeId()) || ( this.getSubInitiativeId()!=null && that.getSubInitiativeId()!=null && this.getSubInitiativeId().equals(that.getSubInitiativeId()) ) )
 && ( (this.getSubInitiativeName()==that.getSubInitiativeName()) || ( this.getSubInitiativeName()!=null && that.getSubInitiativeName()!=null && this.getSubInitiativeName().equals(that.getSubInitiativeName()) ) )
 && ( (this.getKeyElementId()==that.getKeyElementId()) || ( this.getKeyElementId()!=null && that.getKeyElementId()!=null && this.getKeyElementId().equals(that.getKeyElementId()) ) )
 && ( (this.getKeyElementName()==that.getKeyElementName()) || ( this.getKeyElementName()!=null && that.getKeyElementName()!=null && this.getKeyElementName().equals(that.getKeyElementName()) ) )
 && ( (this.getStatusId()==that.getStatusId()) || ( this.getStatusId()!=null && that.getStatusId()!=null && this.getStatusId().equals(that.getStatusId()) ) )
 && ( (this.getStatusDescription()==that.getStatusDescription()) || ( this.getStatusDescription()!=null && that.getStatusDescription()!=null && this.getStatusDescription().equals(that.getStatusDescription()) ) )
 && ( (this.getInvestmentAttributeId()==that.getInvestmentAttributeId()) || ( this.getInvestmentAttributeId()!=null && that.getInvestmentAttributeId()!=null && this.getInvestmentAttributeId().equals(that.getInvestmentAttributeId()) ) )
 && ( (this.getAttributeCategoryId()==that.getAttributeCategoryId()) || ( this.getAttributeCategoryId()!=null && that.getAttributeCategoryId()!=null && this.getAttributeCategoryId().equals(that.getAttributeCategoryId()) ) )
 && ( (this.getCategoryName()==that.getCategoryName()) || ( this.getCategoryName()!=null && that.getCategoryName()!=null && this.getCategoryName().equals(that.getCategoryName()) ) )
 && ( (this.getAttributeGroupId()==that.getAttributeGroupId()) || ( this.getAttributeGroupId()!=null && that.getAttributeGroupId()!=null && this.getAttributeGroupId().equals(that.getAttributeGroupId()) ) )
 && ( (this.getGroupingName()==that.getGroupingName()) || ( this.getGroupingName()!=null && that.getGroupingName()!=null && this.getGroupingName().equals(that.getGroupingName()) ) )
 && ( (this.getInvestmentAttributeCodeId()==that.getInvestmentAttributeCodeId()) || ( this.getInvestmentAttributeCodeId()!=null && that.getInvestmentAttributeCodeId()!=null && this.getInvestmentAttributeCodeId().equals(that.getInvestmentAttributeCodeId()) ) )
 && ( (this.getAttributeName()==that.getAttributeName()) || ( this.getAttributeName()!=null && that.getAttributeName()!=null && this.getAttributeName().equals(that.getAttributeName()) ) )
 && ( (this.getDistributionPercent()==that.getDistributionPercent()) || ( this.getDistributionPercent()!=null && that.getDistributionPercent()!=null && this.getDistributionPercent().equals(that.getDistributionPercent()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getInvestmentId() == null ? 0 : this.getInvestmentId().hashCode() );
         result = 37 * result + ( getInvestmentName() == null ? 0 : this.getInvestmentName().hashCode() );
         result = 37 * result + ( getProgramId() == null ? 0 : this.getProgramId().hashCode() );
         result = 37 * result + ( getProgramName() == null ? 0 : this.getProgramName().hashCode() );
         result = 37 * result + ( getStrategyId() == null ? 0 : this.getStrategyId().hashCode() );
         result = 37 * result + ( getStrategyName() == null ? 0 : this.getStrategyName().hashCode() );
         result = 37 * result + ( getInitiativeId() == null ? 0 : this.getInitiativeId().hashCode() );
         result = 37 * result + ( getInitiativeName() == null ? 0 : this.getInitiativeName().hashCode() );
         result = 37 * result + ( getSubInitiativeId() == null ? 0 : this.getSubInitiativeId().hashCode() );
         result = 37 * result + ( getSubInitiativeName() == null ? 0 : this.getSubInitiativeName().hashCode() );
         result = 37 * result + ( getKeyElementId() == null ? 0 : this.getKeyElementId().hashCode() );
         result = 37 * result + ( getKeyElementName() == null ? 0 : this.getKeyElementName().hashCode() );
         result = 37 * result + ( getStatusId() == null ? 0 : this.getStatusId().hashCode() );
         result = 37 * result + ( getStatusDescription() == null ? 0 : this.getStatusDescription().hashCode() );
         result = 37 * result + ( getInvestmentAttributeId() == null ? 0 : this.getInvestmentAttributeId().hashCode() );
         result = 37 * result + ( getAttributeCategoryId() == null ? 0 : this.getAttributeCategoryId().hashCode() );
         result = 37 * result + ( getCategoryName() == null ? 0 : this.getCategoryName().hashCode() );
         result = 37 * result + ( getAttributeGroupId() == null ? 0 : this.getAttributeGroupId().hashCode() );
         result = 37 * result + ( getGroupingName() == null ? 0 : this.getGroupingName().hashCode() );
         result = 37 * result + ( getInvestmentAttributeCodeId() == null ? 0 : this.getInvestmentAttributeCodeId().hashCode() );
         result = 37 * result + ( getAttributeName() == null ? 0 : this.getAttributeName().hashCode() );
         result = 37 * result + ( getDistributionPercent() == null ? 0 : this.getDistributionPercent().hashCode() );

         return result;
    }


}

