/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.test_20apr.bmgf_investments.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.test_20apr.bmgf_investments.*;

/**
 * Service object for domain model class VwInvestment.
 * @see com.test_20apr.bmgf_investments.VwInvestment
 */

public interface VwInvestmentService {

	/**
	 * Finds all vwinvestments.
	 * 
	 * @return A list of vwinvestments.
	 */
	public Page<VwInvestment> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<VwInvestment> findAll(Pageable pageable);
	
	/**
	 * Finds vwinvestment by id.
	 * 
	 * @param id
	 *            The id of the wanted vwinvestment.
	 * @return The found vwinvestment. If no vwinvestment is found, this method returns
	 *         null.
	 */
	public VwInvestment findById(VwInvestmentId id) throws
	 EntityNotFoundException;

	/**
	 * Retrieve the total count of the vwinvestments in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the vwinvestment.
	 */

	public long countAll();


    public Page<VwInvestment> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

