/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.test_20apr.bmgf_investments2.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.test_20apr.bmgf_investments2.*;

/**
 * Service object for domain model class VwInvestmentAttributesAndCodes.
 * @see com.test_20apr.bmgf_investments2.VwInvestmentAttributesAndCodes
 */

public interface VwInvestmentAttributesAndCodesService {

	/**
	 * Finds all vwinvestmentattributesandcodess.
	 * 
	 * @return A list of vwinvestmentattributesandcodess.
	 */
	public Page<VwInvestmentAttributesAndCodes> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<VwInvestmentAttributesAndCodes> findAll(Pageable pageable);
	
	/**
	 * Finds vwinvestmentattributesandcodes by id.
	 * 
	 * @param id
	 *            The id of the wanted vwinvestmentattributesandcodes.
	 * @return The found vwinvestmentattributesandcodes. If no vwinvestmentattributesandcodes is found, this method returns
	 *         null.
	 */
	public VwInvestmentAttributesAndCodes findById(VwInvestmentAttributesAndCodesId id) throws
	 EntityNotFoundException;

	/**
	 * Retrieve the total count of the vwinvestmentattributesandcodess in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the vwinvestmentattributesandcodes.
	 */

	public long countAll();


    public Page<VwInvestmentAttributesAndCodes> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

