/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.test_20apr.bmgf_investments;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * AttributeCategory generated by hbm2java
 */
@Entity
@Table(name="`AttributeCategory`"
    ,schema="dbo"
)

public class AttributeCategory  implements java.io.Serializable {

    
    private String attributeCategoryId;
    
    private String categoryName;
    
    private Boolean mandatoryAttribute;
    
    private Integer categoryDisplayOrder;
    
    private Set<InvestmentAttribute> investmentAttributes = new HashSet<InvestmentAttribute>(0);
    
    private AttributeGroup attributeGroup;
    
    private Program program;
    
    private Strategy strategy;
    
    private Set<AttributeCategoryCode> attributeCategoryCodes = new HashSet<AttributeCategoryCode>(0);

    public AttributeCategory() {
    }


    @Id 
    

    @Column(name="`AttributeCategoryID`", length=36)
    public String getAttributeCategoryId() {
        return this.attributeCategoryId;
    }
    
    public void setAttributeCategoryId(String attributeCategoryId) {
        this.attributeCategoryId = attributeCategoryId;
    }

    

    @Column(name="`CategoryName`")
    public String getCategoryName() {
        return this.categoryName;
    }
    
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    

    @Column(name="`MandatoryAttribute`")
    public Boolean getMandatoryAttribute() {
        return this.mandatoryAttribute;
    }
    
    public void setMandatoryAttribute(Boolean mandatoryAttribute) {
        this.mandatoryAttribute = mandatoryAttribute;
    }

    

    @Column(name="`CategoryDisplayOrder`", precision=10)
    public Integer getCategoryDisplayOrder() {
        return this.categoryDisplayOrder;
    }
    
    public void setCategoryDisplayOrder(Integer categoryDisplayOrder) {
        this.categoryDisplayOrder = categoryDisplayOrder;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="attributeCategory")
    public Set<InvestmentAttribute> getInvestmentAttributes() {
        return this.investmentAttributes;
    }
    
    public void setInvestmentAttributes(Set<InvestmentAttribute> investmentAttributes) {
        this.investmentAttributes = investmentAttributes;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`AttributeGroupID`")
    public AttributeGroup getAttributeGroup() {
        return this.attributeGroup;
    }
    
    public void setAttributeGroup(AttributeGroup attributeGroup) {
        this.attributeGroup = attributeGroup;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`ProgramID`")
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`StrategyID`")
    public Strategy getStrategy() {
        return this.strategy;
    }
    
    public void setStrategy(Strategy strategy) {
        this.strategy = strategy;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="attributeCategory")
    public Set<AttributeCategoryCode> getAttributeCategoryCodes() {
        return this.attributeCategoryCodes;
    }
    
    public void setAttributeCategoryCodes(Set<AttributeCategoryCode> attributeCategoryCodes) {
        this.attributeCategoryCodes = attributeCategoryCodes;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof AttributeCategory) )
		    return false;

		 AttributeCategory that = (AttributeCategory) o;

		 return ( (this.getAttributeCategoryId()==that.getAttributeCategoryId()) || ( this.getAttributeCategoryId()!=null && that.getAttributeCategoryId()!=null && this.getAttributeCategoryId().equals(that.getAttributeCategoryId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getAttributeCategoryId() == null ? 0 : this.getAttributeCategoryId().hashCode() );

         return result;
    }


}

