/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.test_20apr.bmgf_investments;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * AttributeCategoryCode generated by hbm2java
 */
@Entity
@Table(name="`AttributeCategoryCode`"
    ,schema="dbo"
)

public class AttributeCategoryCode  implements java.io.Serializable {

    
    private String attributeCategoryCodeId;
    
    private String attributeName;
    
    private Integer codeDisplayOrder;
    
    private Set<InvestmentAttributeCode> investmentAttributeCodes = new HashSet<InvestmentAttributeCode>(0);
    
    private AttributeCategory attributeCategory;

    public AttributeCategoryCode() {
    }


    @Id 
    

    @Column(name="`AttributeCategoryCodeID`", length=36)
    public String getAttributeCategoryCodeId() {
        return this.attributeCategoryCodeId;
    }
    
    public void setAttributeCategoryCodeId(String attributeCategoryCodeId) {
        this.attributeCategoryCodeId = attributeCategoryCodeId;
    }

    

    @Column(name="`AttributeName`")
    public String getAttributeName() {
        return this.attributeName;
    }
    
    public void setAttributeName(String attributeName) {
        this.attributeName = attributeName;
    }

    

    @Column(name="`CodeDisplayOrder`", precision=10)
    public Integer getCodeDisplayOrder() {
        return this.codeDisplayOrder;
    }
    
    public void setCodeDisplayOrder(Integer codeDisplayOrder) {
        this.codeDisplayOrder = codeDisplayOrder;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="attributeCategoryCode")
    public Set<InvestmentAttributeCode> getInvestmentAttributeCodes() {
        return this.investmentAttributeCodes;
    }
    
    public void setInvestmentAttributeCodes(Set<InvestmentAttributeCode> investmentAttributeCodes) {
        this.investmentAttributeCodes = investmentAttributeCodes;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`AttributeCategoryID`")
    public AttributeCategory getAttributeCategory() {
        return this.attributeCategory;
    }
    
    public void setAttributeCategory(AttributeCategory attributeCategory) {
        this.attributeCategory = attributeCategory;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof AttributeCategoryCode) )
		    return false;

		 AttributeCategoryCode that = (AttributeCategoryCode) o;

		 return ( (this.getAttributeCategoryCodeId()==that.getAttributeCategoryCodeId()) || ( this.getAttributeCategoryCodeId()!=null && that.getAttributeCategoryCodeId()!=null && this.getAttributeCategoryCodeId().equals(that.getAttributeCategoryCodeId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getAttributeCategoryCodeId() == null ? 0 : this.getAttributeCategoryCodeId().hashCode() );

         return result;
    }


}

