/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.test_20apr.bmgf_investments;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * InvestmentAttributeCode generated by hbm2java
 */
@Entity
@Table(name="`InvestmentAttributeCode`"
    ,schema="dbo"
)

public class InvestmentAttributeCode  implements java.io.Serializable {

    
    private String investmentAttributeCodeId;
    
    private Float distributionPercent;
    
    private Integer codeDisplayOrder;
    
    private AttributeCategoryCode attributeCategoryCode;
    
    private InvestmentAttribute investmentAttribute;

    public InvestmentAttributeCode() {
    }


    @Id 
    

    @Column(name="`InvestmentAttributeCodeID`", length=36)
    public String getInvestmentAttributeCodeId() {
        return this.investmentAttributeCodeId;
    }
    
    public void setInvestmentAttributeCodeId(String investmentAttributeCodeId) {
        this.investmentAttributeCodeId = investmentAttributeCodeId;
    }

    

    @Column(name="`DistributionPercent`", precision=5)
    public Float getDistributionPercent() {
        return this.distributionPercent;
    }
    
    public void setDistributionPercent(Float distributionPercent) {
        this.distributionPercent = distributionPercent;
    }

    

    @Column(name="`CodeDisplayOrder`", precision=10)
    public Integer getCodeDisplayOrder() {
        return this.codeDisplayOrder;
    }
    
    public void setCodeDisplayOrder(Integer codeDisplayOrder) {
        this.codeDisplayOrder = codeDisplayOrder;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`AttributeCategoryCodeID`")
    public AttributeCategoryCode getAttributeCategoryCode() {
        return this.attributeCategoryCode;
    }
    
    public void setAttributeCategoryCode(AttributeCategoryCode attributeCategoryCode) {
        this.attributeCategoryCode = attributeCategoryCode;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`InvestmentAttributeID`")
    public InvestmentAttribute getInvestmentAttribute() {
        return this.investmentAttribute;
    }
    
    public void setInvestmentAttribute(InvestmentAttribute investmentAttribute) {
        this.investmentAttribute = investmentAttribute;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof InvestmentAttributeCode) )
		    return false;

		 InvestmentAttributeCode that = (InvestmentAttributeCode) o;

		 return ( (this.getInvestmentAttributeCodeId()==that.getInvestmentAttributeCodeId()) || ( this.getInvestmentAttributeCodeId()!=null && that.getInvestmentAttributeCodeId()!=null && this.getInvestmentAttributeCodeId().equals(that.getInvestmentAttributeCodeId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getInvestmentAttributeCodeId() == null ? 0 : this.getInvestmentAttributeCodeId().hashCode() );

         return result;
    }


}

