/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.test_20apr.bmgf_investments;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Strategy generated by hbm2java
 */
@Entity
@Table(name="`Strategy`"
    ,schema="dbo"
)

public class Strategy  implements java.io.Serializable {

    
    private String strategyId;
    
    private String strategyName;
    
    private Set<AttributeCategory> attributeCategories = new HashSet<AttributeCategory>(0);
    
    private Set<Investment> investments = new HashSet<Investment>(0);
    
    private Set<Initiative> initiatives = new HashSet<Initiative>(0);
    
    private Program program;

    public Strategy() {
    }


    @Id 
    

    @Column(name="`StrategyID`", length=36)
    public String getStrategyId() {
        return this.strategyId;
    }
    
    public void setStrategyId(String strategyId) {
        this.strategyId = strategyId;
    }

    

    @Column(name="`StrategyName`")
    public String getStrategyName() {
        return this.strategyName;
    }
    
    public void setStrategyName(String strategyName) {
        this.strategyName = strategyName;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="strategy")
    public Set<AttributeCategory> getAttributeCategories() {
        return this.attributeCategories;
    }
    
    public void setAttributeCategories(Set<AttributeCategory> attributeCategories) {
        this.attributeCategories = attributeCategories;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="strategy")
    public Set<Investment> getInvestments() {
        return this.investments;
    }
    
    public void setInvestments(Set<Investment> investments) {
        this.investments = investments;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="strategy")
    public Set<Initiative> getInitiatives() {
        return this.initiatives;
    }
    
    public void setInitiatives(Set<Initiative> initiatives) {
        this.initiatives = initiatives;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`ProgramID`")
    public Program getProgram() {
        return this.program;
    }
    
    public void setProgram(Program program) {
        this.program = program;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Strategy) )
		    return false;

		 Strategy that = (Strategy) o;

		 return ( (this.getStrategyId()==that.getStrategyId()) || ( this.getStrategyId()!=null && that.getStrategyId()!=null && this.getStrategyId().equals(that.getStrategyId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getStrategyId() == null ? 0 : this.getStrategyId().hashCode() );

         return result;
    }


}

