/*Copyright (c) 2016-2017 testing.com All Rights Reserved.
 This software is the confidential and proprietary information of testing.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with testing.com*/

package com.test_20apr.bmgf_investments;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * VwInvestmentId generated by hbm2java
 */
@Embeddable
public class VwInvestmentId  implements java.io.Serializable {

    
    private Integer investmentId;
    
    private String investmentName;
    
    private Integer programId;
    
    private String programName;
    
    private Integer strategyId;
    
    private String strategyName;
    
    private Integer initiativeId;
    
    private String initiativeName;
    
    private Integer subInitiativeId;
    
    private String subInitiativeName;
    
    private Integer keyElementId;
    
    private String keyElementName;
    
    private Integer statusId;
    
    private String statusDescription;
    
    private String notes;

    public VwInvestmentId() {
    }


    public Integer getInvestmentId() {
        return this.investmentId;
    }
    
    public void setInvestmentId(Integer investmentId) {
        this.investmentId = investmentId;
    }
    public String getInvestmentName() {
        return this.investmentName;
    }
    
    public void setInvestmentName(String investmentName) {
        this.investmentName = investmentName;
    }
    public Integer getProgramId() {
        return this.programId;
    }
    
    public void setProgramId(Integer programId) {
        this.programId = programId;
    }
    public String getProgramName() {
        return this.programName;
    }
    
    public void setProgramName(String programName) {
        this.programName = programName;
    }
    public Integer getStrategyId() {
        return this.strategyId;
    }
    
    public void setStrategyId(Integer strategyId) {
        this.strategyId = strategyId;
    }
    public String getStrategyName() {
        return this.strategyName;
    }
    
    public void setStrategyName(String strategyName) {
        this.strategyName = strategyName;
    }
    public Integer getInitiativeId() {
        return this.initiativeId;
    }
    
    public void setInitiativeId(Integer initiativeId) {
        this.initiativeId = initiativeId;
    }
    public String getInitiativeName() {
        return this.initiativeName;
    }
    
    public void setInitiativeName(String initiativeName) {
        this.initiativeName = initiativeName;
    }
    public Integer getSubInitiativeId() {
        return this.subInitiativeId;
    }
    
    public void setSubInitiativeId(Integer subInitiativeId) {
        this.subInitiativeId = subInitiativeId;
    }
    public String getSubInitiativeName() {
        return this.subInitiativeName;
    }
    
    public void setSubInitiativeName(String subInitiativeName) {
        this.subInitiativeName = subInitiativeName;
    }
    public Integer getKeyElementId() {
        return this.keyElementId;
    }
    
    public void setKeyElementId(Integer keyElementId) {
        this.keyElementId = keyElementId;
    }
    public String getKeyElementName() {
        return this.keyElementName;
    }
    
    public void setKeyElementName(String keyElementName) {
        this.keyElementName = keyElementName;
    }
    public Integer getStatusId() {
        return this.statusId;
    }
    
    public void setStatusId(Integer statusId) {
        this.statusId = statusId;
    }
    public String getStatusDescription() {
        return this.statusDescription;
    }
    
    public void setStatusDescription(String statusDescription) {
        this.statusDescription = statusDescription;
    }
    public String getNotes() {
        return this.notes;
    }
    
    public void setNotes(String notes) {
        this.notes = notes;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof VwInvestmentId) )
		    return false;

		 VwInvestmentId that = (VwInvestmentId) o;

         return ( (this.getInvestmentId()==that.getInvestmentId()) || ( this.getInvestmentId()!=null && that.getInvestmentId()!=null && this.getInvestmentId().equals(that.getInvestmentId()) ) )
 && ( (this.getInvestmentName()==that.getInvestmentName()) || ( this.getInvestmentName()!=null && that.getInvestmentName()!=null && this.getInvestmentName().equals(that.getInvestmentName()) ) )
 && ( (this.getProgramId()==that.getProgramId()) || ( this.getProgramId()!=null && that.getProgramId()!=null && this.getProgramId().equals(that.getProgramId()) ) )
 && ( (this.getProgramName()==that.getProgramName()) || ( this.getProgramName()!=null && that.getProgramName()!=null && this.getProgramName().equals(that.getProgramName()) ) )
 && ( (this.getStrategyId()==that.getStrategyId()) || ( this.getStrategyId()!=null && that.getStrategyId()!=null && this.getStrategyId().equals(that.getStrategyId()) ) )
 && ( (this.getStrategyName()==that.getStrategyName()) || ( this.getStrategyName()!=null && that.getStrategyName()!=null && this.getStrategyName().equals(that.getStrategyName()) ) )
 && ( (this.getInitiativeId()==that.getInitiativeId()) || ( this.getInitiativeId()!=null && that.getInitiativeId()!=null && this.getInitiativeId().equals(that.getInitiativeId()) ) )
 && ( (this.getInitiativeName()==that.getInitiativeName()) || ( this.getInitiativeName()!=null && that.getInitiativeName()!=null && this.getInitiativeName().equals(that.getInitiativeName()) ) )
 && ( (this.getSubInitiativeId()==that.getSubInitiativeId()) || ( this.getSubInitiativeId()!=null && that.getSubInitiativeId()!=null && this.getSubInitiativeId().equals(that.getSubInitiativeId()) ) )
 && ( (this.getSubInitiativeName()==that.getSubInitiativeName()) || ( this.getSubInitiativeName()!=null && that.getSubInitiativeName()!=null && this.getSubInitiativeName().equals(that.getSubInitiativeName()) ) )
 && ( (this.getKeyElementId()==that.getKeyElementId()) || ( this.getKeyElementId()!=null && that.getKeyElementId()!=null && this.getKeyElementId().equals(that.getKeyElementId()) ) )
 && ( (this.getKeyElementName()==that.getKeyElementName()) || ( this.getKeyElementName()!=null && that.getKeyElementName()!=null && this.getKeyElementName().equals(that.getKeyElementName()) ) )
 && ( (this.getStatusId()==that.getStatusId()) || ( this.getStatusId()!=null && that.getStatusId()!=null && this.getStatusId().equals(that.getStatusId()) ) )
 && ( (this.getStatusDescription()==that.getStatusDescription()) || ( this.getStatusDescription()!=null && that.getStatusDescription()!=null && this.getStatusDescription().equals(that.getStatusDescription()) ) )
 && ( (this.getNotes()==that.getNotes()) || ( this.getNotes()!=null && that.getNotes()!=null && this.getNotes().equals(that.getNotes()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getInvestmentId() == null ? 0 : this.getInvestmentId().hashCode() );
         result = 37 * result + ( getInvestmentName() == null ? 0 : this.getInvestmentName().hashCode() );
         result = 37 * result + ( getProgramId() == null ? 0 : this.getProgramId().hashCode() );
         result = 37 * result + ( getProgramName() == null ? 0 : this.getProgramName().hashCode() );
         result = 37 * result + ( getStrategyId() == null ? 0 : this.getStrategyId().hashCode() );
         result = 37 * result + ( getStrategyName() == null ? 0 : this.getStrategyName().hashCode() );
         result = 37 * result + ( getInitiativeId() == null ? 0 : this.getInitiativeId().hashCode() );
         result = 37 * result + ( getInitiativeName() == null ? 0 : this.getInitiativeName().hashCode() );
         result = 37 * result + ( getSubInitiativeId() == null ? 0 : this.getSubInitiativeId().hashCode() );
         result = 37 * result + ( getSubInitiativeName() == null ? 0 : this.getSubInitiativeName().hashCode() );
         result = 37 * result + ( getKeyElementId() == null ? 0 : this.getKeyElementId().hashCode() );
         result = 37 * result + ( getKeyElementName() == null ? 0 : this.getKeyElementName().hashCode() );
         result = 37 * result + ( getStatusId() == null ? 0 : this.getStatusId().hashCode() );
         result = 37 * result + ( getStatusDescription() == null ? 0 : this.getStatusDescription().hashCode() );
         result = 37 * result + ( getNotes() == null ? 0 : this.getNotes().hashCode() );

         return result;
    }


}

